Fix max memory bytes/words mismatch
zotonic/depcache pull request #3
Opened 2017-04-05 14:57 UTC by ddeboer

While memory_max was defined in MB, the ets table size check was done for number of words instead. This caused the depcache size limit to allow 4 (32 bit) or 8 (64 bit) as much memory use as defined.

2017-04-05 15:19 UTC, mworrell requested changes

2017-04-05 15:19 UTC, mworrell commented on src/depcache.erl
> +    MemoryMaxWords = 1024 * 1024 * MemoryMaxMbs / erlang:system_info(wordsize),
Should that be `div` ?  Now the result is a float.

2017-04-06 06:30 UTC, ddeboer commented
Changed division from `/` to `div`.

2017-04-06 10:41 UTC, mworrell approved these changes

2017-04-06 10:41 UTC, merged

2017-04-06 11:02 UTC, arjan commented
I can add you as package owners on hex.pm for depcache, which email addresses do I need for that?

2017-04-06 11:10 UTC, ddeboer commented
See https://github.com/ddeboer 😉 

I don’t think Zotonic installs depcache through Hex. Or are you talking about other users?